services:
  - type: web
    name: gani-eleke-backend
    runtime: image
    repo: https://github.com/lukman2008/gani-eleke-frontend
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production